import { readFile } from "node:fs/promises"
import { join, resolve } from "node:path"

import { uploadImage } from "./ipfsService"

/**
 * Pin the artwork for an action type, once, and remember the CID.
 *
 * Quests generated by the model had no banner at all, so a quest a player accepted opened onto a
 * blank rectangle. The model is not asked to invent an image and no image is fetched from the
 * internet: this pins the same artwork the site already draws for that action type, from
 * `apps/web/public/actions`, so a quest looks the same wherever it is read from, including in a
 * wallet or an explorer that only has the pinned metadata.
 *
 * The CID is cached per process. Pinata returns the same CID for identical bytes anyway, so a cache
 * miss costs a redundant upload rather than a wrong answer.
 */
const SLUGS: Record<number, string> = {
  0: "portal",
  1: "uniswap-swap",
  2: "erc20-transfer",
  3: "aave-supply",
  4: "aave-borrow",
  5: "penguinswap-swap",
  6: "wrap-native",
}

// This package builds to CommonJS, so `__dirname` is the portable one here. It is src/services in
// development and dist/services once built, and the repository root is four levels up from either.
const ART_DIR = resolve(__dirname, "../../../..", "apps/web/public/actions")

const cache = new Map<number, string>()

export async function pinActionBanner(actionType: number): Promise<string | undefined> {
  const cached = cache.get(actionType)
  if (cached) return cached

  const slug = SLUGS[actionType]
  if (!slug) return undefined

  try {
    const bytes = await readFile(join(ART_DIR, `${slug}-banner.png`))
    const uri = await uploadImage(bytes, "image/png", `vael-action-${slug}`)
    cache.set(actionType, uri)
    return uri
  } catch (error) {
    // A quest without a banner is worse-looking, not wrong. Never fail a quest over its picture.
    console.warn(`[actionArt] could not pin the banner for action ${actionType}: ${error}`)
    return undefined
  }
}
