import { Router } from "express"
import { z } from "zod"

import { hasServiceEnv } from "../config/env"
import { generatePersonalQuest, profileOf } from "../services/personalQuest"

export const personalQuestRouter: Router = Router()

const generateSchema = z.object({
  address: z.string().regex(/^0x[a-fA-F0-9]{40}$/),
  cadence: z.enum(["daily", "weekly", "manual"]).default("manual"),
})

/**
 * GET /ai/profile/:address
 *
 * Exactly what the generator is given, and nothing else. Worth exposing on its own: a quest is
 * only auditable if the evidence behind it can be read separately from the quest.
 */
personalQuestRouter.get("/profile/:address", async (req, res, next) => {
  try {
    const address = String(req.params.address)
    if (!/^0x[a-fA-F0-9]{40}$/.test(address)) {
      return res.status(400).json({ message: "address must be a 20-byte hex address" })
    }
    return res.json(await profileOf(address))
  } catch (error) {
    next(error)
  }
})

/**
 * POST /ai/personal-quest
 *
 * The manual trigger. The cron uses the same code path, so a quest generated by hand and one
 * generated on a schedule are the same thing.
 */
personalQuestRouter.post("/personal-quest", async (req, res, next) => {
  try {
    if (!hasServiceEnv()) {
      return res.status(503).json({ message: "Groq and Pinata are not configured" })
    }
    const parsed = generateSchema.safeParse(req.body)
    if (!parsed.success) {
      return res.status(400).json({ message: "Invalid input", errors: parsed.error.issues })
    }
    const result = await generatePersonalQuest(parsed.data.address, parsed.data.cadence)
    return res.json(result)
  } catch (error) {
    next(error)
  }
})
