/**
 * Pin the loot item icons and their metadata to IPFS through Pinata.
 *
 *   pnpm --filter @vael/api pin-items
 *
 * Reads the catalogue at `apps/web/src/content/items.json`, which is generated by
 * `apps/web/scripts/make-items.mjs` and is the single source of truth for an item's stats. The
 * result is written to `apps/api/scripts/item-cids.json`, which the registration script reads.
 *
 * Re-running is safe: IPFS is content addressed, so identical bytes pin to the same CID.
 */
import "dotenv/config"

import { readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

const PIN_FILE = "https://api.pinata.cloud/pinning/pinFileToIPFS"
const PIN_JSON = "https://api.pinata.cloud/pinning/pinJSONToIPFS"

const REPO_ROOT = join(__dirname, "../../..")
const CATALOGUE = join(REPO_ROOT, "apps/web/src/content/items.json")
const OUT = join(__dirname, "item-cids.json")

interface CatalogueItem {
  slug: string
  name: string
  slot: number
  rarity: number
  strength: number
  agility: number
  intellect: number
  blurb: string
  image: string
}

interface Catalogue {
  slots: string[]
  rarities: string[]
  items: CatalogueItem[]
}

function jwt(): string {
  const token = process.env.PINATA_JWT
  if (!token) throw new Error("PINATA_JWT is not set")
  return token
}

async function pinFile(path: string, name: string): Promise<string> {
  const type = name.endsWith(".webp") ? "image/webp" : "image/png"
  const body = new FormData()
  body.append("file", new Blob([new Uint8Array(readFileSync(path))], { type }), name)
  body.append("pinataMetadata", JSON.stringify({ name }))

  const response = await fetch(PIN_FILE, {
    method: "POST",
    headers: { Authorization: `Bearer ${jwt()}` },
    body,
  })
  if (!response.ok) throw new Error(`pin ${name} failed: ${response.status} ${await response.text()}`)
  return ((await response.json()) as { IpfsHash: string }).IpfsHash
}

async function pinJson(content: unknown, name: string): Promise<string> {
  const response = await fetch(PIN_JSON, {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: `Bearer ${jwt()}` },
    body: JSON.stringify({ pinataMetadata: { name }, pinataContent: content }),
  })
  if (!response.ok) throw new Error(`pin ${name} failed: ${response.status} ${await response.text()}`)
  return ((await response.json()) as { IpfsHash: string }).IpfsHash
}

async function main() {
  const catalogue = JSON.parse(readFileSync(CATALOGUE, "utf8")) as Catalogue
  const records: Record<string, unknown>[] = []

  for (const item of catalogue.items) {
    const extension = item.image.split(".").pop() ?? "webp"
    const imageCid = await pinFile(join(REPO_ROOT, "apps/web/public", item.image), `vael-item-${item.slug}.${extension}`)

    const metadata = {
      name: item.name,
      description:
        `${item.blurb} A Vael loot item. Items drop from defeated raid bosses, where rarity ` +
        "follows your share of damage the chain verified, and from arena duels.",
      image: `ipfs://${imageCid}`,
      attributes: [
        { trait_type: "Rarity", value: catalogue.rarities[item.rarity] },
        { trait_type: "Slot", value: catalogue.slots[item.slot] },
        { trait_type: "Strength", value: item.strength },
        { trait_type: "Agility", value: item.agility },
        { trait_type: "Intellect", value: item.intellect },
      ],
    }

    const metadataCid = await pinJson(metadata, `vael-item-${item.slug}.json`)
    records.push({ ...item, imageCid, metadataCid })
    console.log(`${item.slug.padEnd(18)} image ${imageCid}  metadata ${metadataCid}`)
  }

  writeFileSync(OUT, `${JSON.stringify({ items: records }, null, 2)}\n`)
  console.log(`\nwrote ${OUT}`)
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
